<?php

namespace App\Helpers;

class HttpStatus
{
    const STATUS_SUCCESS_OK = 200;
    const STATUS_SUCCESS_CREATED = 201;
    const STATUS_SUCCESS_UPDATED = 202;
    const STATUS_SUCCESS_DELETED = 200;

    const STATUS_ERROR_CUSTOM = 400;
    const STATUS_ERROR_NO_ACCESS = 403;
    const STATUS_ERROR_AUTH = 401;
    const STATUS_ERROR_NOT_FOUND = 404;
    const STATUS_ERROR_METHOD_NOT_ALLOWED = 405;
    const STATUS_ERROR_VERSION_FAIL = 406;
    const STATUS_ERROR_INVALID_HEADER = 409;
    const STATUS_ERROR_VALIDATION = 422;
    const STATUS_ERROR_BLOCKED = 450;
    const STATUS_ERROR_UNVERIFIED = 451;
    const STATUS_ERROR_SERVER = 500;
}
